// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBmhCIW7y6g7udvPvU_jcudvmhyoc-9I',
    appId: '1:230750693641:web:706ed652bd3302b3188bd8',
    messagingSenderId: '230750693641',
    projectId: 'todo-a-mil-mae',
    authDomain: 'todo-a-mil-mae.firebaseapp.com',
    storageBucket: 'todo-a-mil-mae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFsZnExr1sHcpXNOr-xszCx4SymsT1xE',
    appId: '1:230750693641:android:0334ceb2ab425d88188bd8',
    messagingSenderId: '230750693641',
    projectId: 'todo-a-mil-mae',
    storageBucket: 'todo-a-mil-mae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6TQn9jk3zZwWC5n10R0NPbM84kAArrY',
    appId: '1:230750693641:ios:efbc56cc961f9ce6188bd8',
    messagingSenderId: '230750693641',
    projectId: 'todo-a-mil-mae',
    storageBucket: 'todo-a-mil-mae.firebasestorage.app',
    iosBundleId: 'com.example.todoAMilMae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6TQn9jk3zZwWC5n10R0NPbM84kAArrY',
    appId: '1:230750693641:ios:efbc56cc961f9ce6188bd8',
    messagingSenderId: '230750693641',
    projectId: 'todo-a-mil-mae',
    storageBucket: 'todo-a-mil-mae.firebasestorage.app',
    iosBundleId: 'com.example.todoAMilMae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBmhCIW7y6g7udvPvU_jcudvmhyoc-9I',
    appId: '1:230750693641:web:f2b3da3026c64d49188bd8',
    messagingSenderId: '230750693641',
    projectId: 'todo-a-mil-mae',
    authDomain: 'todo-a-mil-mae.firebaseapp.com',
    storageBucket: 'todo-a-mil-mae.firebasestorage.app',
  );
}
